### ISSUE TITLE
Ajout d'un autorun au slider

### ISSUE THREAD

**Issue by dbiron** [Slemaitre56/Site-vitrine-Boostrap---Projet-Formation#4]
Pourquoi ne pas rajouter un petit autorun au slider.
sa fait plus joli =)

voilà à quoi je pense. Un simple bout de code à rajouter à la fin du code du slider. Il suffira juste de rajouter un onload="autorun();" a la balise body de la page index afin qu'il se lance automatiquement au chargement de la page.
```javascript
    function autorun(){
        setInterval("droite(1)", 3000);
    }

**Comment by Slemaitre56** [comment]
très bonne idée !!
